# Generated by Django 3.2.7 on 2021-09-25 04:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todaylog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('soju', '소주'), ('beer', '맥주'), ('makgeolli', '막걸리'), ('liquor', '양주'), ('wine', '와인')], default='soju', max_length=10)),
                ('rating', models.TextField()),
                ('rating_content', models.TextField(max_length=100)),
                ('content', models.TextField(max_length=1000)),
                ('pub_date', models.DateTimeField()),
                ('public', models.CharField(choices=[('private', '비공개'), ('public', '공개')], default='private', max_length=10)),
                ('image', models.ImageField(upload_to='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=1000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post_id', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, to='todaylog.todaylog')),
            ],
        ),
    ]
