# Generated by Django 3.2.7 on 2021-09-25 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todaylog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todaylog',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
