# Generated by Django 3.2.7 on 2021-09-25 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todaylog', '0003_remove_todaylog_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todaylog',
            name='author',
        ),
        migrations.RemoveField(
            model_name='todaylog',
            name='content',
        ),
        migrations.RemoveField(
            model_name='todaylog',
            name='image',
        ),
        migrations.RemoveField(
            model_name='todaylog',
            name='public',
        ),
        migrations.RemoveField(
            model_name='todaylog',
            name='rating',
        ),
    ]
