# Generated by Django 3.2.7 on 2021-09-25 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alcohol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alc', models.FloatField(max_length=3)),
                ('cup', models.FloatField(max_length=6)),
                ('bottle', models.FloatField(max_length=6)),
                ('alc_type', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
            ],
        ),
    ]
